# Generated by Django 5.2 on 2025-05-06 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourtDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision_id', models.CharField(max_length=150, unique=True)),
                ('decision_number', models.CharField(max_length=150)),
                ('proceeding_number', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('absent', 'Absent'), ('done', 'Done')], default='absent', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
